### ISSUE TITLE
Caminho de imagens quebrados em "produção"

### ISSUE THREAD

**Issue by girol** [uspdev/slides#13]
Quando pulicados no GitHub Pages, as imagens aparecem quebradas.

**Comment by thiagogomesverissimo** [comment]
Acho que se vc usar o ./ antes do caminho resolve, tipo: src="./images/github.png"

**Comment by girol** [comment]
@thiagogomesverissimo funcionou! Eu cheguei a consertar nos meus, pq vi que um slide seu tava com o `.` na frente e tava funcionando, mas reportei a issue pq tinha slide seu quebrado também.

**Comment by girol** [comment]
@thiagogomesverissimo , check [this](https://uspdev.github.io/slides/laravel_basico/#/bootstrap-intro)

**Comment by thiagogomesverissimo** [comment]
Sim, eu estou arrumando.
