### ISSUE TITLE
Melhorar processo de geração de slides com present.sh

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/slides#5]
Como o script present.sh supõe que o prez esteja instalado localmente, criar um packages.json e remover a informação do readme.md sobre instalar o prez globalmente (neste caso colocar a instrução : node install)

**Comment by thiagogomesverissimo** [comment]
@girol

**Comment by girol** [comment]
Resolvido em ccae7dfeff258164c85e57ce9053915c8c14ac5b
